server:
  port: 9080

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password: 1
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          likelion-oidc:
            provider: likelion
            client-id: likelion-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:9080/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: likelion-oidc
          likelion-auth-code:
            provider: likelion
            client-id: likelion-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:9080/authorized"
            scope: read
            client-name: likelion-auth-code
        provider:
          likelion:
            issuer-uri: http://localhost:10000

logging:
  level:
    tis.communityproject: debug
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace
